export const GET_CURRENCIES = "GET_CURRENCIES"
export const SET_LOADER = "SET_LOADER"
export const SET_RELOAD = "SET_RELOAD"
export const SET_ERROR = "SET_ERROR"
export const SET_ERROR_RELOAD = "SET_ERROR_RELOAD"
